language: swift

osx_image: xcode9.3
xcode_project: Bootcamp.xcodeproj

cache:
  - bundler
  - cocoapods

script:
  - swiftlint
  - xcodebuild -workspace Bootcamp.xcworkspace -scheme BootcampTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' test | xcpretty
  - xcodebuild -workspace Bootcamp.xcworkspace -scheme BootcampUITests -sdk iphonesimulator build-for-testing -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.3' test | xcpretty

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  slack: web-bootcamp:wyKIbU3rSC2tjbCh99Nnq1aE
